xgboost_optimize_params: true
xgboost_default_params:
  n_jobs: -1
  use_label_encoder: false

xgboost_model_params:
  eval_metric: "auc"
    # - "auc"
    # - "error"
  n_estimators: 500
    # - 500
    # - 1000
    # - 1500
  max_depth: 3
    # - 3
    # - 5
    # - 6
    # - 10
  reg_lambda: 0.05
    # - 0.001
    # - 0.01
    # - 0.05
    # - 0.1
    # - 0.5
  gamma: 0.01
    # - 0.01
    # - 0.1
    # - 0.5
    # - 1.0
  min_child_weight: 2
    # - 1
    # - 2
    # - 5
    # - 7
    # - 10
  learning_rate: 0.05
    # - 0.01
    # - 0.05
    # - 0.1
    # - 0.2
  subsample: 0.7
    # - 0.5
    # - 0.7
    # - 1.0
  colsample_bytree: 0.5
    # - 0.5
    # - 0.7
    # - 1.0
  objective: "binary:logistic"
    # - "reg:squarederror"
    # - "binary:logistic"
