# if `logreg_optixgboost_optimize_paramsmize_params` is true, then the parameters are gonna be optimized in runtime
xgboost_optimize_params: false

# apply these parameters regardless of optimization or not
xgboost_default_params:
  n_jobs: -1
  use_label_encoder: false
  seed: 0

# if `xgboost_optimize_params` is false, then use the parameters defined below
# if not using `subsample` and `colsample_bytree` parameters the model is deterministic, but increases the chance of overfitting
xgboost_model_params:
  eval_metric: "auc"
  n_estimators: 100
  max_depth: 3
  reg_lambda: 1
  gamma: 0.1
  min_child_weight: 0.01
  learning_rate: 0.1
  objective: "binary:logistic"
  sampling_method: "uniform"
  tree_method: "auto"
  booster: "gbtree"
