xgboost_optimize_params: false
xgboost_default_params:
  n_jobs: -1
  use_label_encoder: false

# parameters not being considered so far:
# max_delta_step, colsample_bylevel, colsample_bynode, reg_alpha, scale_pos_weight, updater
# refresh_leaf, process_type, grow_policy, max_leaves, max_bin, predictor, num_parallel_tree
# monotone_constraints, interaction_constraints

# if not using `subsample` and `colsample_bytree` the model is deterministic, but increases the chance of overfitting
xgboost_model_params:
  eval_metric: "auc"
  n_estimators: 500
  max_depth: 3
  reg_lambda: 0.05
  gamma: 0.01
  min_child_weight: 2.0
  learning_rate: 0.05
  # subsample: 0.7
  # colsample_bytree: 0.5
  objective: "binary:logistic"
  sampling_method: "uniform"
  tree_method: "auto"
