# if `logreg_optixgboost_optimize_paramsmize_params` is true, then the parameters are gonna be optimized in runtime
xgboost_optimize_params: false

# apply these parameters regardless of optimization or not
xgboost_default_params:
  n_jobs: -1
  use_label_encoder: false
  seed: 0

# if `xgboost_optimize_params` is false, then use the parameters defined below
# if not using `subsample` and `colsample_bytree` parameters the model is deterministic, but increases the chance of overfitting
xgboost_model_params:
  eval_metric: "error"
  n_estimators: 1300
  max_depth: 5
  reg_lambda: 0.37926901907322497
  gamma: 0.029763514416313176
  min_child_weight: 3.359818286283781
  learning_rate: 0.07847599703514611
  objective: "reg:logistic"
  sampling_method: "uniform"
  tree_method: "auto"
  booster: "gbtree"
